# Creating folder
- name: Creating folder in control node
  file:
    path: /home/piolo/Desktop/hands_on_7.1/log_files/manage_node_one/
    state: directory

# Passing the log files from managed node
- name: Copying log files
  fetch:
    src: "/var/log/{{ item }}"
    dest: /home/piolo/Desktop/hands_on_7.1/log_files/manage_node_one/
    flat: yes
  with_items:
    - alternatives.log
    - auth.log
    - bootstrap.log
    - btmp
    - dpkg.log
    - faillog
    - fontconfig.log
    - gpu-manager.log
    - kern.log
    - lastlog
    - syslog
    - syslog.1
    - tallylog
    - ubuntu-advantage.log
    - ubuntu-advantage-timer.log
    - vboxpostinstall.log
    - wtmp

